### ISSUE TITLE
"Success" message is posted to Slack too early

### ISSUE THREAD

**Issue by rfwatson** [mixlr/capistrano-slack#2]
When deploying, the ":+1: production" message appears to be posted to Slack at the start of the `deploy:restart` stage, not at the end.

### Steps to recreate

1. Deploy to production
1. Watch the Slack notifications and Airbrussh logs

### Expected behaviour

The ":+1: production" message is only posted _after_ the restarting process has successfully completed on all servers

### Actual behaviour

The message is posted at the time the restarting process begins

**Comment by hubb** [comment]
we could hook after [`deploy:finishing`](https://github.com/mixlr/capistrano-slack/blob/master/lib/capistrano/tasks/slack.rake#L8) instead, and potentially add after `deploy:finishing_rollback` as well

**Comment by rfwatson** [comment]
Also not sure why this regressed as it worked as expected in the pre-gem days?

**Comment by rfwatson** [comment]
Ah ok, the hooks did change - any objections if the start hook is reverted back to `starting` (instead of `started`) as the "Deploy starting" message is also now being posted noticeably later in the sequence than it used to.

https://github.com/mixlr/capistrano-slack/blob/bb189d8fc8dac0ff179e3d51f79b2a62fd5eb838/lib/capistrano/tasks/slack.rake#L4

**Comment by hubb** [comment]
updated #3 (at [3a23e](https://github.com/mixlr/capistrano-slack/pull/3/commits/3a23e4ebfd071bd96d9a8d75802e7c9288a6b310))
